name: mental_health_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  http: 0.13.6
  shared_preferences: ^2.0.0
  fl_chart: ^0.70.2
  url_launcher: ^6.1.10
  webview_flutter: ^4.10.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dialog_flowtter: ^0.3.3-nullsafety.0
  just_audio: ^0.9.44
  audio_service: ^0.18.16
  just_audio_background: ^0.0.1-beta.14

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/app_icon/app_icon.png"

flutter:
  uses-material-design: true
  