name: mental_health_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  http: ^1.3.0
  shared_preferences: ^2.0.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/app_icon/app_icon.png"

flutter:
  uses-material-design: true
